# Generated by Django 3.2 on 2022-10-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_activitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
